apiVersion: v1
kind: Secret
metadata:
  name: argocd-github-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/ianmurphy1/argocd-eks
