---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secret
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretsmanager-store
    kind: ClusterSecretStore
  target:
    name: argocd-secret
  dataFrom:
    - extract:
        key: eks/argocd/admin-creds
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-app-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretsmanager-store
    kind: ClusterSecretStore
  target:
    name: argocd-github-app-creds
  dataFrom:
    - extract:
        key: eks/argocd/github-app-creds
---
